name: 'Python Assessment Unit Test'

on:
  workflow_dispatch:

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Pip install prerequesteis
        run: |
          pip install -r requirements.txt

      - name: Run Unit Test
        run: |
          cd calender_module
          python unittest_calender.py
      
